export type AppRow={n:number;name:string;cat:string;does:string;auth:string;access:"Self-serve"|"Friction"|"Gated";api:string;mcp:boolean;verdict:"Build now"|"Build with friction"|"Outreach first";blocker:string;url:string};
const cats=["CRM & Sales","Support","Communications","Marketing","Ecommerce","Data & SEO","Developer","Productivity","Finance","AI & Media"];
const raw:string[][]=[
["Salesforce","CRM platform","OAuth2","Friction","Broad REST/SOAP/GraphQL","Admin/edition setup","https://developer.salesforce.com/docs/apis"],
["HubSpot","CRM and marketing suite","OAuth2 / private token","Self-serve","Broad REST","—","https://developers.hubspot.com/docs/api/overview"],
["Pipedrive","Sales pipeline CRM","OAuth2 / API token","Self-serve","Broad REST","Trial/account","https://developers.pipedrive.com/docs/api/v1"],
["Attio","Flexible modern CRM","OAuth2 / token","Self-serve","Broad REST","—","https://docs.attio.com/rest-api/overview"],
["Twenty","Open-source CRM","API key","Self-serve","REST / GraphQL","—","https://docs.twenty.com/developers"],
["Podio","Collaborative work CRM","OAuth2","Self-serve","Broad REST","—","https://developers.podio.com/"],
["Zoho CRM","Sales CRM","OAuth2","Self-serve","Broad REST","OAuth complexity","https://www.zoho.com/crm/developer/docs/api/v7/"],
["Close","Sales engagement CRM","API key / Basic","Friction","Broad REST","Paid account","https://developer.close.com/"],
["Copper","Google-centric CRM","API key + email","Friction","REST","Paid plan","https://developer.copper.com/"],
["DealCloud","Deal management platform","OAuth2 / token","Gated","REST","Customer credentials","https://api.docs.dealcloud.com/"],
["Zendesk","Customer support suite","OAuth2 / token / Basic","Self-serve","Broad REST","—","https://developer.zendesk.com/api-reference/"],
["Intercom","Customer messaging platform","OAuth2 / token","Self-serve","Broad REST","App review for public","https://developers.intercom.com/docs/references/rest-api/"],
["Freshdesk","Helpdesk software","API key / OAuth2","Self-serve","Broad REST","—","https://developers.freshdesk.com/api/"],
["Front","Shared inbox platform","OAuth2 / token","Self-serve","Broad REST","—","https://dev.frontapp.com/reference/introduction"],
["Pylon","B2B support platform","API key","Friction","REST","Customer plan","https://docs.usepylon.com/pylon-docs/developer/api"],
["LiveAgent","Customer support desk","API key","Friction","REST","Plan feature","https://support.liveagent.com/840770-Complete-API-reference"],
["Plain","API-first support platform","API key","Self-serve","GraphQL","—","https://www.plain.com/docs/api-reference/introduction"],
["Help Scout","Shared inbox and docs","OAuth2 / API key","Self-serve","REST","—","https://developer.helpscout.com/mailbox-api/"],
["Gorgias","Ecommerce helpdesk","OAuth2 / Basic","Friction","REST","Paid account","https://developers.gorgias.com/reference/introduction"],
["Gladly","Enterprise service platform","OAuth2","Gated","REST","Enterprise customer","https://developer.gladly.com/"],
["Slack","Team messaging","OAuth2 / token","Self-serve","Broad Web API","Workspace install","https://api.slack.com/docs"],
["Twilio","Programmable communications","API key / Basic","Self-serve","Broad REST","Usage cost","https://www.twilio.com/docs/usage/api"],
["Zoho Cliq","Team chat","OAuth2","Self-serve","REST","—","https://www.zoho.com/cliq/help/restapi/v2/"],
["Lark","Collaboration suite","OAuth2 / app token","Self-serve","Broad REST","App approval","https://open.larksuite.com/document/home/index"],
["Pumble","Team chat","Token / webhooks","Friction","Limited API","Surface maturity","https://pumble.com/help/integrations/pumble-api/"],
["Discord","Community messaging","OAuth2 / bot token","Self-serve","Broad REST/Gateway","Bot permissions","https://discord.com/developers/docs/intro"],
["Telegram","Messaging platform","Bot token","Self-serve","Bot API","Bot-only scope","https://core.telegram.org/bots/api"],
["WhatsApp Business","Business messaging","OAuth2 / system token","Friction","Graph API","Business verification","https://developers.facebook.com/docs/whatsapp/cloud-api/"],
["Aircall","Cloud phone system","OAuth2 / Basic","Friction","REST","Partner/public app review","https://developer.aircall.io/api-references/"],
["Vonage","Communications APIs","API key / JWT","Self-serve","Broad REST","Usage cost","https://developer.vonage.com/en/api"],
["Google Ads","Advertising platform","OAuth2 + developer token","Friction","Broad REST/gRPC","Production token review","https://developers.google.com/google-ads/api/docs/api-policy/access-levels"],
["Meta Ads","Advertising platform","OAuth2 token","Friction","Broad Graph API","App/business review","https://developers.facebook.com/docs/marketing-apis/"],
["LinkedIn Ads","Professional advertising","OAuth2","Gated","Broad REST","Product access approval","https://learn.microsoft.com/en-us/linkedin/marketing/quick-start"],
["GoHighLevel","Agency marketing CRM","OAuth2 / token","Friction","Broad REST","Plan/marketplace setup","https://marketplace.gohighlevel.com/docs/"],
["Mailchimp","Email marketing","OAuth2 / API key","Self-serve","Broad REST","—","https://mailchimp.com/developer/marketing/docs/fundamentals/"],
["Klaviyo","Marketing automation","OAuth2 / API key","Self-serve","Broad REST","—","https://developers.klaviyo.com/en/reference/api_overview"],
["systeme.io","Funnel and email builder","API key","Friction","REST","Paid/API availability","https://developer.systeme.io/"],
["Pinterest","Visual discovery ads","OAuth2","Friction","REST","App review","https://developers.pinterest.com/docs/api/v5/"],
["Threads","Social network","OAuth2","Friction","Graph API","App review and scopes","https://developers.facebook.com/docs/threads/"],
["SendGrid","Transactional email","API key","Self-serve","Broad REST","Usage limits","https://www.twilio.com/docs/sendgrid/api-reference"],
["Shopify","Commerce platform","OAuth2 / token","Self-serve","Broad GraphQL/REST","App review for public","https://shopify.dev/docs/api"],
["WooCommerce","WordPress commerce","Basic / API keys","Self-serve","Broad REST","Store admin access","https://woocommerce.github.io/woocommerce-rest-api-docs/"],
["BigCommerce","Commerce platform","OAuth2 / token","Self-serve","Broad REST/GraphQL","Store access","https://developer.bigcommerce.com/docs/rest"],
["Salesforce Commerce Cloud","Enterprise commerce","OAuth2","Gated","Broad REST","Enterprise tenant","https://developer.salesforce.com/docs/commerce/commerce-api/overview"],
["Adobe Commerce","Enterprise ecommerce","OAuth2 / token","Friction","REST / GraphQL","Hosting/admin setup","https://developer.adobe.com/commerce/webapi/rest/"],
["Squarespace","Website commerce","OAuth2 / API key","Friction","Commerce REST","Plan limits","https://developers.squarespace.com/commerce-apis"],
["Ecwid","Embedded commerce","OAuth2 / token","Self-serve","Broad REST","—","https://docs.ecwid.com/api-reference/"],
["Gumroad","Creator commerce","OAuth2","Self-serve","REST","Narrower surface","https://gumroad.com/api"],
["Amazon Selling Partner","Marketplace operations","OAuth2 (LWA)","Gated","Broad REST","Developer/profile review","https://developer-docs.amazon.com/sp-api/docs/onboarding-overview"],
["fanbasis","Creator monetization","Other","Gated","No clear public API","Private access","https://www.fanbasis.com/"],
["DataForSEO","SEO data provider","Basic","Self-serve","Broad REST","Paid credits","https://docs.dataforseo.com/v3/"],
["SE Ranking","SEO platform","API key","Friction","REST","Business plan","https://seranking.com/api.html"],
["Ahrefs","SEO intelligence","API key","Friction","Broad REST","Enterprise plan/credits","https://docs.ahrefs.com/docs/api/reference/introduction"],
["MrScraper","Web scraping API","API key","Self-serve","REST","Usage credits","https://docs.mrscraper.com/"],
["Apify","Web automation platform","Token","Self-serve","Broad REST","Usage credits","https://docs.apify.com/api/v2"],
["Firecrawl","Web crawl and extract","API key","Self-serve","REST","Usage credits","https://docs.firecrawl.dev/api-reference/introduction"],
["Bright Data","Web data platform","API key / token","Friction","Broad REST","Paid zone/compliance","https://docs.brightdata.com/api-reference/introduction"],
["Sherlock","Username search CLI","None","Self-serve","CLI, no hosted API","Wrap/host CLI","https://github.com/sherlock-project/sherlock"],
["Waterfall.io","Contact data enrichment","API key","Gated","Private/partner API","Sales access","https://waterfall.io/"],
["Clay","GTM data workspace","API key / webhook","Friction","Limited/public endpoints","Surface and plan","https://www.clay.com/university/guide/clay-api"],
["GitHub","Code collaboration","OAuth2 / PAT / App","Self-serve","Broad REST/GraphQL","—","https://docs.github.com/en/rest"],
["Vercel","Deployment platform","OAuth2 / token","Self-serve","Broad REST","—","https://vercel.com/docs/rest-api"],
["Netlify","Web deployment platform","OAuth2 / token","Self-serve","Broad REST","—","https://docs.netlify.com/api-and-cli-guides/api-guides/get-started-with-api/"],
["Cloudflare","Edge cloud platform","OAuth2 / API token","Self-serve","Very broad REST","Scope safety","https://developers.cloudflare.com/api/"],
["Supabase","Backend platform","API key / OAuth2","Self-serve","REST/GraphQL/admin APIs","Scope safety","https://supabase.com/docs/guides/api"],
["Neo4j","Graph database","Basic / bearer","Self-serve","Query + REST","Deployment endpoint","https://neo4j.com/docs/query-api/current/"],
["Snowflake","Cloud data warehouse","OAuth2 / key pair / password","Friction","SQL + REST","Account/admin setup","https://docs.snowflake.com/en/developer-guide/sql-api/index"],
["MongoDB Atlas","Managed database","API key / OAuth2","Self-serve","Broad REST","Scope safety","https://www.mongodb.com/docs/atlas/api/"],
["Datadog","Observability platform","API + app keys / OAuth2","Self-serve","Broad REST","Plan-specific endpoints","https://docs.datadoghq.com/api/latest/"],
["Sentry","Error monitoring","OAuth2 / token","Self-serve","Broad REST","—","https://docs.sentry.io/api/"],
["Notion","Knowledge workspace","OAuth2 / token","Self-serve","Broad REST","Page sharing model","https://developers.notion.com/reference/intro"],
["Airtable","No-code database","OAuth2 / PAT","Self-serve","Broad REST","Rate limits","https://airtable.com/developers/web/api/introduction"],
["Linear","Issue tracking","OAuth2 / API key","Self-serve","Broad GraphQL","—","https://linear.app/developers/graphql"],
["Jira","Issue and project tracking","OAuth2 / token / Basic","Self-serve","Broad REST","Cloud vs server variants","https://developer.atlassian.com/cloud/jira/platform/rest/v3/intro/"],
["Asana","Work management","OAuth2 / PAT","Self-serve","Broad REST","—","https://developers.asana.com/docs"],
["Monday.com","Work operating system","OAuth2 / token","Self-serve","Broad GraphQL","Plan/API complexity","https://developer.monday.com/api-reference/docs"],
["ClickUp","Project management","OAuth2 / token","Self-serve","Broad REST","—","https://developer.clickup.com/docs/"],
["Coda","Collaborative docs","OAuth2 / token","Self-serve","Broad REST","—","https://coda.io/developers/apis/v1"],
["Smartsheet","Work management","OAuth2 / token","Self-serve","Broad REST","—","https://developers.smartsheet.com/api/smartsheet/openapi"],
["Harvest","Time tracking","OAuth2 / token","Self-serve","Broad REST","—","https://help.getharvest.com/api-v2/"],
["Stripe","Payments platform","API key / OAuth2","Self-serve","Very broad REST","Financial action safety","https://docs.stripe.com/api"],
["Plaid","Financial data network","API keys / token","Self-serve","Broad REST","Production approval","https://plaid.com/docs/api/"],
["Binance","Crypto exchange","API key + secret","Self-serve","Broad REST/WebSocket","Region and trading safety","https://developers.binance.com/docs/binance-spot-api-docs"],
["Paygent Connect","Payments connector","Other","Gated","No clear public docs","Vendor access","https://www.paygent.com/"],
["iPayX","AI payments platform","API key","Gated","Docs not reliably public","Access/identity ambiguity","https://ipayx.ai/docs"],
["QuickBooks","Accounting platform","OAuth2","Self-serve","Broad REST","Production app review","https://developer.intuit.com/app/developer/qbo/docs/get-started"],
["Xero","Accounting platform","OAuth2","Self-serve","Broad REST","App/connection limits","https://developer.xero.com/documentation/api/accounting/overview"],
["Brex","Corporate finance","OAuth2 / token","Friction","Broad REST","Customer/admin access","https://developer.brex.com/openapi/"],
["Ramp","Spend management","OAuth2","Gated","Broad REST","Customer/partner approval","https://docs.ramp.com/"],
["PitchBook","Private-market research","API key","Gated","Enterprise data API","Contract/contact sales","https://pitchbook.com/products/data/financial-data-and-api"],
["NotebookLM","AI research notebook","OAuth2","Gated","Enterprise API","Enterprise/allowlist","https://cloud.google.com/gemini/enterprise/notebooklm-enterprise/docs/api"],
["Otter AI","Meeting transcription","OAuth2","Self-serve","Public API + MCP","New surface / account","https://help.otter.ai/hc/en-us/articles/35287607569687-Otter-MCP-Server"],
["Fathom","AI meeting assistant","OAuth2 / API key","Friction","REST/webhooks","Plan/access","https://developers.fathom.ai/"],
["Consensus","Research search","OAuth2","Gated","No broad public API","Partner access","https://consensus.app/"],
["Reducto","Document parsing","API key","Self-serve","Broad REST","Usage credits","https://docs.reducto.ai/"],
["Devin","AI software engineer","API token","Friction","REST + MCP","Paid account/org setup","https://docs.devin.ai/api-reference/authentication"],
["Higgsfield","AI content suite","Token / CLI auth","Friction","CLI/API surface","Product maturity","https://higgsfield.ai/cli"],
["Mermaid CLI","Diagram rendering CLI","None","Self-serve","CLI, no hosted API","Wrap/host CLI","https://github.com/mermaid-js/mermaid-cli"],
["YouTube Transcript","Transcript extraction API","API key","Self-serve","Narrow REST","Third-party dependency","https://transcriptapi.com/docs"],
["Grain","Meeting intelligence","OAuth2 / PAT","Self-serve","Broad REST + MCP","—","https://developers.grain.com/"],
];
const mcpNames=new Set(["GitHub","Cloudflare","Sentry","Notion","Linear","Stripe","Otter AI","Devin","Grain"]);
export const apps:AppRow[]=raw.map((r,i)=>{const access=r[3] as AppRow["access"];return{n:i+1,name:r[0],cat:cats[Math.floor(i/10)],does:r[1],auth:r[2],access,api:r[4],mcp:mcpNames.has(r[0]),verdict:access==="Self-serve"?"Build now":access==="Friction"?"Build with friction":"Outreach first",blocker:r[5],url:r[6]}});

